import { BrainstormForm, AIResults } from '../types';
import { TYPES, PRO_DEPTH } from '../constants/prompts';
import { ll } from './formatters';

export const buildReportMd = (
  pn: string,
  form: BrainstormForm,
  results: AIResults,
  provN: string,
  mL: string,
  dep: number
): string => {
  const now = new Date().toLocaleString('ja-JP');
  const ses = form.sessionType === 'other' ? form.customSession : TYPES[form.sessionType];
  let md = `# AI Strategic Brainstorm Report\n\n`;
  md += `- **プロジェクト**: ${pn}\n`;
  md += `- **プロダクト/サービス**: ${form.productService}\n`;
  md += `- **セッション種別**: ${ses}\n`;
  md += `- **分析深度**: ${PRO_DEPTH[dep]?.label ?? `Lv${dep}`}\n`;
  md += `- **使用モデル**: ${provN} / ${mL}\n`;
  md += `- **生成日時**: ${now}\n\n`;
  
  md += `## 目標\n${form.teamGoals}\n\n`;
  
  const iss = form.issues.filter(x => x.text.trim());
  if (iss.length) {
    md += `## 課題\n`;
    iss.forEach(x => {
      md += `- **${x.text}**${x.detail ? `: ${x.detail}` : ''}${
        x.sub?.filter(Boolean).length ? '\n' + x.sub.filter(Boolean).map(s => `  - ${s}`).join('\n') : ''
      }\n`;
    });
    md += '\n';
  }
  
  if (results.keyIssue) {
    md += `## 最重要イシュー\n\n`;
    if (results.funnelStage) md += `**ボトルネック段階**: ${results.funnelStage}\n\n`;
    md += `${results.keyIssue}\n\n`;
  }

  md += `---\n\n## AI分析\n\n${results.understanding}\n\n---\n\n## 戦略アイデア\n\n`;
  
  results.ideas.forEach((d, i) => {
    md += `### ${i + 1}. ${d.title}\n\n${d.description}\n\n| 優先度 | 工数 | インパクト |\n|---|---|---|\n| ${ll(d.priority)} | ${ll(d.effort)} | ${ll(d.impact)} |\n\n`;
  });
  
  if (results.refinements?.length) {
    md += `---\n\n## ブラッシュアップ\n\n`;
    results.refinements.forEach((r, i) => {
      if (results.refinements!.length > 1) md += `### ${i + 1}. レビュー: ${r.review}\n\n`;
      else md += `> レビュー: ${r.review}\n\n`;
      md += `${r.answer}\n\n`;
    });
  } else if (results.refinement) {
    md += `---\n\n## ブラッシュアップ\n\n${results.refinement}\n`;
  }
  
  if (results.deepDives?.length) {
    md += `---\n\n## 深掘り\n\n`;
    results.deepDives.forEach((dd, i) => {
      md += `### ${i + 1}. ${dd.question}\n\n${dd.answer}\n\n`;
    });
  } else if (results.deepDive) {
    md += `---\n\n## 深掘り\n\n${results.deepDive}\n`;
  }
  
  md += `\n---\n*Generated by AI Strategic Brainstorm*`;
  return md;
};

export const mdToTxt = (md: string): string =>
  md
    .replace(/^# (.*$)/gm, '$1')
    .replace(/^## (.*$)/gm, '■ $1')
    .replace(/^### (.*$)/gm, '  $1')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/^- (.*$)/gm, '・$1')
    .replace(/\|/g, ' ')
    .replace(/[-]{3,}/g, '────────────────────')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

export const buildReportCsv = (
  pn: string,
  form: BrainstormForm,
  results: AIResults,
  mL: string,
  dep: number
): string => {
  const esc = (s: string) => `"${s.replace(/"/g, '""')}"`;
  const ses = form.sessionType === 'other' ? form.customSession : TYPES[form.sessionType];
  const rows: string[] = [];
  rows.push('No,タイトル,説明,優先度,工数,インパクト');
  results.ideas.forEach((d, i) => {
    rows.push(`${i + 1},${esc(d.title)},${esc(d.description)},${d.priority},${d.effort},${d.impact}`);
  });
  rows.push('');
  rows.push(`プロジェクト,${esc(pn)}`);
  rows.push(`プロダクト/サービス,${esc(form.productService)}`);
  rows.push(`セッション種別,${esc(ses)}`);
  rows.push(`分析深度,${PRO_DEPTH[dep]?.label ?? `Lv${dep}`}`);
  rows.push(`使用モデル,${esc(mL)}`);
  rows.push(`生成日時,${new Date().toLocaleString('ja-JP')}`);
  return rows.join('\n');
};

export const printReport = (txt: string, pn: string) => {
  const w = window.open('', '_blank');
  if (!w) return;
  w.document.write(
    `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${pn}</title><style>body{font-family:-apple-system,'Hiragino Sans',sans-serif;max-width:780px;margin:32px auto;padding:0 20px;color:#1a1a1a;line-height:1.8;font-size:13px}pre{white-space:pre-wrap;font-family:inherit}@media print{body{margin:16px}}</style></head><body><pre>${txt}</pre></body></html>`,
  );
  w.document.close();
  setTimeout(() => w.print(), 300);
};

export const dlFile = (c: string, fn: string, mime: string) => {
  const b = new Blob(['\uFEFF' + c], { type: `${mime};charset=utf-8` });
  const u = URL.createObjectURL(b);
  Object.assign(document.createElement('a'), { href: u, download: fn }).click();
  URL.revokeObjectURL(u);
};
