import { BrainstormForm, AIResults } from '../types';
import { TYPES, DEPTH } from '../constants/prompts';
import { ll } from './formatters';

export const buildReportMd = (
  pn: string,
  form: BrainstormForm,
  results: AIResults,
  provN: string,
  mL: string,
  dep: number
): string => {
  const now = new Date().toLocaleString('ja-JP');
  const ses = form.sessionType === 'other' ? form.customSession : TYPES[form.sessionType];
  const tl = form.tlMode === 'period' ? `${form.tlStart || '?'} 〜 ${form.tlEnd || '?'}` : (form.tlDead || '未指定');
  
  let md = `# AI Strategic Brainstorm Report\n\n`;
  md += `- **プロジェクト**: ${pn}\n`;
  md += `- **プロダクト/サービス**: ${form.productService}\n`;
  md += `- **セッション種別**: ${ses}\n`;
  md += `- **タイムライン**: ${tl}\n`;
  md += `- **分析深度**: ${DEPTH[dep].label}\n`;
  md += `- **使用モデル**: ${provN} / ${mL}\n`;
  md += `- **生成日時**: ${now}\n\n`;
  
  md += `## 目標\n${form.teamGoals}\n\n`;
  
  const iss = form.issues.filter(x => x.text.trim());
  if (iss.length) {
    md += `## 課題\n`;
    iss.forEach(x => {
      md += `- **${x.text}**${x.detail ? `: ${x.detail}` : ''}${
        x.sub?.filter(Boolean).length ? '\n' + x.sub.filter(Boolean).map(s => `  - ${s}`).join('\n') : ''
      }\n`;
    });
    md += '\n';
  }
  
  md += `---\n\n## AI分析\n\n${results.understanding}\n\n---\n\n## 戦略アイデア\n\n`;
  
  results.ideas.forEach((d, i) => {
    md += `### ${i + 1}. ${d.title}\n\n${d.description}\n\n| 優先度 | 工数 | インパクト |\n|---|---|---|\n| ${ll(d.priority)} | ${ll(d.effort)} | ${ll(d.impact)} |\n\n`;
  });
  
  if (results.refinement) {
    md += `---\n\n## ブラッシュアップ\n\n${results.refinement}\n`;
  }
  
  if (results.deepDive) {
    md += `---\n\n## 深掘り\n\n${results.deepDive}\n`;
  }
  
  md += `\n---\n*Generated by AI Strategic Brainstorm*`;
  return md;
};

export const dlFile = (c: string, fn: string, mime: string) => {
  const b = new Blob(['\uFEFF' + c], { type: `${mime};charset=utf-8` });
  const u = URL.createObjectURL(b);
  Object.assign(document.createElement('a'), { href: u, download: fn }).click();
  URL.revokeObjectURL(u);
};
